# -*- coding: utf-8 -*-
"""Encode every figure a chart embeds into pom2/assets/figures/, and write the manifest.

Purpose: turn the ![[embeds]] in the chart regions into shipped JPEGs.
Author:  Noor Simsam
Date:    2026-09-15
Input:   the vault lecture notes (POM2_VAULT), read-only
Output:  pom2/assets/figures/<hash>.jpg (or .svg, copied as is), and pom2/data/figures.json mapping vault name -> asset

Unlike a question picture, a chart figure is NOT inlined as a data: URI. Three
reasons, all specific to notes:

  * data/notes/<block>.json is fetched whole when the notes tab opens. endo.json
    is 352 KB today; ten inlined figures would quadruple it on every page load.
  * that file is regenerated by charts_from_vault.py on every rebuild, and
    base64 on one line defeats git's delta compression.
  * the questions side already shows the failure mode - the cortisol figure is
    byte-identical in four of them, because that format has no way to share one.

Naming the file after the hash of its own bytes gives sharing for free: two
lectures embedding the same picture resolve to the same asset.

This script owns the Pillow dependency so the four rebuild scripts keep the
"no dependencies" promise in tools/README.md. It runs before charts_from_vault.py,
which only reads the manifest.

It cannot tell a cadaveric image from a clinical photograph, and does not try.
That call is made by looking at the picture; see the pom2-week skill. Every
newly-encoded file is printed, so a new one is never added unseen.
"""

import argparse
import hashlib
import io
import json
import logging
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from PIL import Image

import charts_from_vault as cfv
from embed_image import MAX_WIDTH, compress, resolve

LOG = logging.getLogger("figures")

# The URL is relative to the page that carries it, which lives in pom2/;
# the directory it is written to is that same path from the repo root.
ASSET_URL = "assets/figures"
ASSET_DIR = os.path.join("pom2", *ASSET_URL.split("/"))
MANIFEST = cfv.FIGURES_PATH

# A figure spans the note's full column, where a question picture sits in a
# narrower one, so it gets a larger budget than embed_image's 100 KB. This is
# a file on disk that the browser caches, not bytes inside the JSON.
MAX_KB = 220

# The upper-year flowcharts (Maggie Prenger's Obsidian canvas exports) are
# 4000-10000px wide with small labels. At 900px their text is unreadable even
# through "Open full size", so they ship wider. Named rather than detected by
# source width: 47 slide crops and anatomy plates are just as wide and read
# fine at 900, and re-encoding them would only cost bandwidth.
FLOWCHARTS = {
    "Approach to a Thyroid Nodule.png",
    "Approach to Amenorrhea.png",
    "Approach to CNS Infections (meningitis & encephalitis).png",
    "Approach to Hypocalcemia and Hypercalcemia.png",
    "Approach to Hypogonadism.png",
    "Approach to Precocious Puberty.png",
    "Calcium Homeostasis.png",
    "Diagnosis of Adrenal Insufficiency.png",
    "Prevention of Macrovascular Complications in DM.png",
    "Thyroid Function Test Outcomes.png",
}
FLOWCHART_MAX_WIDTH = 2400
FLOWCHART_MAX_KB = 700


def embeds_in(region):
    """Every image embed that is alone on its line, in source order."""
    out = []
    for line in region.split("\n"):
        m = cfv.FIG_LINE.match(line)
        if m:
            out.append(m.group(1).strip())
    return out


def wanted(slugs):
    """name -> [lectures that embed it], across every chart in the blocks."""
    found = {}
    for slug in slugs:
        folder = os.path.join(cfv.VAULT, cfv.BLOCK_FOLDER[slug])
        if not os.path.isdir(folder):
            sys.stderr.write("missing block folder: %s\n" % folder)
            continue
        for week in sorted(os.listdir(folder)):
            wd = os.path.join(folder, week)
            if not os.path.isdir(wd):
                continue
            for fn in sorted(os.listdir(wd)):
                if not fn.endswith(".md"):
                    continue
                path = os.path.join(wd, fn)
                try:
                    src = io.open(path, encoding="utf-8").read()
                except (OSError, UnicodeDecodeError) as exc:
                    sys.stderr.write("unreadable: %s (%s)\n" % (path, exc))
                    continue
                region = cfv.chart_region(src)
                if region is None:
                    continue
                for name in embeds_in(region):
                    found.setdefault(name, []).append(fn[:-3])
    return found


# An SVG drawn for a chart (tools/class_tree_svg.py) is already small and is
# text, so it ships byte for byte: rasterizing it would blur the very labels it
# was drawn as vectors to keep sharp. Its size comes from its own root element.
SVG_SIZE = re.compile(r'<svg\b[^>]*?\bwidth="([\d.]+)"[^>]*?\bheight="([\d.]+)"')


def copy_svg(name):
    """Ship an SVG unchanged, named after its bytes. Returns the manifest row."""
    raw = open(resolve(name), "rb").read()
    m = SVG_SIZE.search(raw[:2000].decode("utf-8", "replace"))
    if not m:
        raise SystemExit("%s has no width and height on its <svg>" % name)
    width, height = int(float(m.group(1))), int(float(m.group(2)))

    digest = hashlib.md5(raw).hexdigest()[:12]
    row = {"src": "%s/%s.svg" % (ASSET_URL, digest), "w": width, "h": height}
    dest = os.path.join(ASSET_DIR, digest + ".svg")
    if os.path.exists(dest):
        return row, False
    with open(dest, "wb") as fh:
        fh.write(raw)
    LOG.info("%-58s -> %s  %.0f KB  %dx%d  svg",
             name, digest + ".svg", len(raw) / 1024.0, width, height)
    return row, True


def encode_asset(name, max_kb, max_width):
    """Compress, name the file after its bytes, write it. Returns the manifest row."""
    if name.lower().endswith(".svg"):
        return copy_svg(name)
    path = resolve(name)
    budget = max_kb * 1024
    raw, width, quality, ok = compress(path, max_width, lambda b: len(b) <= budget)
    if not ok:
        LOG.warning("%s will not fit under %d KB; shipping %.1f KB at %dpx q%d",
                    name, max_kb, len(raw) / 1024.0, width, quality)

    digest = hashlib.md5(raw).hexdigest()[:12]
    rel = "%s/%s.jpg" % (ASSET_URL, digest)
    dest = os.path.join(ASSET_DIR, digest + ".jpg")

    height = Image.open(io.BytesIO(raw)).height
    row = {"src": rel, "w": width, "h": height}

    if os.path.exists(dest):
        return row, False
    with open(dest, "wb") as fh:
        fh.write(raw)
    LOG.info("%-58s -> %s  %.0f KB  %dx%d  q%d",
             name, digest + ".jpg", len(raw) / 1024.0, width, height, quality)
    return row, True


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("slugs", nargs="*", default=None,
                    help="blocks to scan (default: all five)")
    ap.add_argument("--max-kb", type=int, default=MAX_KB,
                    help="file size budget in KB (default %d)" % MAX_KB)
    ap.add_argument("--max-width", type=int, default=MAX_WIDTH,
                    help="widest the figure may ship (default %d)" % MAX_WIDTH)
    args = ap.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stderr)
    slugs = args.slugs or list(cfv.BLOCK_FOLDER)

    if not os.path.isdir(ASSET_DIR):
        os.makedirs(ASSET_DIR)

    manifest, new, failed = {}, 0, 0
    for name, lectures in sorted(wanted(slugs).items()):
        try:
            if name in FLOWCHARTS:
                row, was_new = encode_asset(name, FLOWCHART_MAX_KB, FLOWCHART_MAX_WIDTH)
            else:
                row, was_new = encode_asset(name, args.max_kb, args.max_width)
        except SystemExit as exc:
            # resolve() raises this when the picture is not in the vault; one
            # missing file should not stop the other figures being written
            sys.stderr.write("%s\n" % exc)
            failed += 1
            continue
        manifest[name] = row
        new += 1 if was_new else 0

    io.open(MANIFEST, "w", encoding="utf-8", newline="\n").write(
        json.dumps(manifest, indent=1, ensure_ascii=False, sort_keys=True))

    used = set(r["src"].rsplit("/", 1)[-1] for r in manifest.values())
    orphans = sorted(f for f in os.listdir(ASSET_DIR)
                     if f.endswith((".jpg", ".svg")) and f not in used)
    for f in orphans:
        sys.stderr.write("orphan (no chart embeds it): %s/%s\n" % (ASSET_DIR, f))

    print("figures %3d in manifest, %d new, %d missing, %d orphaned"
          % (len(manifest), new, failed, len(orphans)))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
