# -*- coding: utf-8 -*-
"""Back the portal up into the medwiki vault.

Purpose: write what the portal ships but the vault lacks back into the vault, so
         the vault holds everything: FoM and PoM 1's curated notes as charts at
         the top of each lecture note, and every question family that has no
         vault note of its own as a question note.
Author:  Noor Sims
Date:    2026-09-27
Input:   <course>/data/notes/*.json and <course>/data/questions/*.json
Output:  the vault's FoM / PoM 1 lecture notes (a chart region prepended),
         00 - Practice Questions/<course>/<Family> - <Block>.md, and pictures
         copied into Attachments/

    python tools/vault_backup.py charts      [--dry-run]
    python tools/vault_backup.py questions   [--dry-run]

Which way the data flows depends on the course, and that is why this is one
tool with two narrow jobs rather than a general sync:

* PoM 2's notes and its module, weekly, workbook and Meds 2029 questions are
  written IN the vault and exported to the portal, so they are never touched
  here. Only PoM 2's HippoNotes and Schulich Reviews sets, which were authored
  straight into the portal JSON, are backed up.
* FoM, PoM 1 and T2C were built from PDFs and curated in the portal JSON, so
  the JSON is their source and the vault copy is the backup.
* PoM 2's Off-curriculum set has no note of its own. A question moved there
  (see tools/curriculum_audit.py) stays in the note of the family it came from,
  its `offCurriculum.from`, under the same week, with its flag as a warning.
  One that came from a vault-owned family is marked in the vault instead.

A chart is only ever added to a lecture note that has none, never merged into
one. A question note is only ever overwritten if this tool wrote it, which the
GENERATED marker on its second-to-last line proves.
"""

import argparse
import hashlib
import io
import json
import os
import re
import shutil
import sys
from datetime import date
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import portal  # noqa: E402

VAULT = Path(os.environ.get("MEDWIKI", "/mnt/c/Users/nsims/medwiki"))
LECTURES = VAULT / "01 - Lectures"
QUESTIONS = VAULT / "00 - Practice Questions"
ATTACH = VAULT / "Attachments"

GENERATED = "<!-- generated by preclerkship tools/vault_backup.py - edit the portal JSON, then rerun -->"

# course -> (vault course folder, {block slug: block folder}) for the chart job
CHART_COURSES = {
    "fom": ("99 - FoM", {"b1": "Block 1", "b2": "Block 2", "b3": "Block 3", "b4": "Block 4"}),
    "pom1": ("99 - PoM 1", {"cardio": "01 - Cardiology", "resp": "02 - Respirology",
                            "ent": "03 - ENT", "gi": "04 - Gastroenterology",
                            "gu": "05 - Genitourinary"}),
}

# where each block's curated notes came from, for the chart's provenance line
NOTE_SOURCE = {
    "fom": "the 2021-22 FoM summative notes, curated for the portal",
    "cardio": "Nicole's upper-year PoM 1 notes, curated for the portal",
    "resp": "Nicole's upper-year PoM 1 notes, curated for the portal",
    "gi": "Nicole's upper-year PoM 1 notes, curated for the portal",
}

# the vault's own spelling of each family, as in "Module Questions - Endocrinology"
FAMILY_NOTE = {
    "module": "Module Questions", "weekly": "Weekly Quizzes", "ra": "Readiness Assessments",
    "sa": "Self-Assessments", "meds2024": "Meds 2024 Bank", "new": "New Questions",
    "workbook": "Preclerkship Workbook", "meds2029": "New Questions",
    "reviews": "Schulich Reviews", "hipponotes": "HippoNotes",
}

# families already written in the vault and exported from it; never regenerated
VAULT_OWNED = {("pom2", f) for f in ("module", "weekly", "workbook", "meds2029")}

# a set that files its questions under the note of the family each came from
OFF = "offcurriculum"


def home_family(q):
    """The family whose note a question is backed up in: its own, or for an
    off-curriculum question the one it was moved out of."""
    if q.get("family") == OFF:
        return (q.get("offCurriculum") or {}).get("from") or OFF
    return q.get("family")

COURSE_FOLDER = {"fom": "FoM", "pom1": "PoM 1", "t2c": "T2C"}   # pom2 stays flat, as it is today


# ---------- html -> Obsidian markdown ----------

class Node:
    def __init__(self, tag, attrs=None, parent=None):
        self.tag, self.attrs, self.parent, self.kids = tag, dict(attrs or []), parent, []


class Tree(HTMLParser):
    VOID = {"br", "img", "hr"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = self.cur = Node("root")

    def handle_starttag(self, tag, attrs):
        n = Node(tag, attrs, self.cur)
        self.cur.kids.append(n)
        if tag not in self.VOID:
            self.cur = n

    def handle_endtag(self, tag):
        n = self.cur
        while n is not self.root and n.tag != tag:
            n = n.parent
        if n is not self.root:
            self.cur = n.parent

    def handle_data(self, data):
        self.cur.kids.append(data)


class Md:
    """Render a parsed fragment. `figure` maps an img src to an embed name."""

    def __init__(self, course, figure):
        self.course, self.figure = course, figure

    def inline(self, n, cell=False):
        out = []
        for k in n.kids:
            if isinstance(k, str):
                t = re.sub(r"\s+", " ", k)
                out.append(t.replace("|", "\\|") if cell else t)
                continue
            inner = self.inline(k, cell)
            tag = k.tag
            if tag in ("strong", "b"):
                out.append("**%s**" % inner.strip() if inner.strip() else inner)
            elif tag in ("em", "i"):
                out.append("*%s*" % inner.strip() if inner.strip() else inner)
            elif tag == "mark":
                out.append("==%s==" % inner)
            elif tag == "code":
                out.append("`%s`" % inner)
            elif tag in ("sup", "sub", "u"):
                out.append("<%s>%s</%s>" % (tag, inner, tag))
            elif tag == "br":
                out.append("<br>" if cell else "\n")
            elif tag == "img":
                out.append(self.image(k))
            elif tag in ("ul", "ol") and cell:
                items = [self.inline(li, cell).strip() for li in k.kids if isinstance(li, Node)]
                out.append("<br>".join("• " + i for i in items))
            elif tag in ("p", "div", "li", "h5", "h4", "h6") and cell:
                out.append(inner.strip() + "<br>")
            else:
                out.append(inner)
        s = "".join(out)
        return re.sub(r"(<br>)+$", "", s) if cell else s

    def image(self, n):
        name = self.figure(n.attrs.get("src", ""))
        return ("![[%s]]" % name) if name else "*[picture missing: %s]*" % n.attrs.get("alt", "")

    def blocks(self, n, depth=0):
        """Block-level render; returns a list of paragraphs (strings)."""
        paras, run = [], []

        def flush():
            s = "".join(run).strip()
            if s:
                paras.append(s)
            run.clear()

        for k in n.kids:
            if isinstance(k, str) or k.tag in ("strong", "b", "em", "i", "span", "a", "mark",
                                               "code", "sup", "sub", "u", "br"):
                run.append(self.inline(_wrap(k)))
                continue
            flush()
            if k.tag in ("p", "div"):
                paras.extend(self.blocks(k, depth))
            elif k.tag in ("h4", "h5", "h6"):
                paras.append("##### " + self.inline(k).strip())
            elif k.tag in ("ul", "ol"):
                paras.append(self.listing(k, depth))
            elif k.tag == "table":
                paras.append(self.table(k))
            elif k.tag == "figure":
                img = _find(k, "img")
                cap = _find(k, "figcaption")
                s = self.image(img) if img else ""
                if cap:
                    s += "\n*%s*" % self.inline(cap).strip()
                paras.append(s)
            elif k.tag == "img":
                paras.append(self.image(k))
            else:
                paras.extend(self.blocks(k, depth))
        flush()
        return paras

    def listing(self, n, depth):
        lines, i = [], 0
        for li in n.kids:
            if not isinstance(li, Node) or li.tag != "li":
                continue
            i += 1
            mark = ("%d." % i) if n.tag == "ol" else "-"
            head = Node("x")
            subs = []
            for k in li.kids:
                if isinstance(k, Node) and k.tag in ("ul", "ol"):
                    subs.append(k)
                else:
                    head.kids.append(k)
            text = " ".join(p.replace("\n", " ") for p in self.blocks(head, depth)).strip()
            lines.append("    " * depth + mark + " " + text)
            for s in subs:
                lines.append(self.listing(s, depth + 1))
        return "\n".join(lines)

    def table(self, n):
        rows = []
        for tr in _all(n, "tr"):
            rows.append([self.inline(c, cell=True).strip() or " "
                         for c in tr.kids if isinstance(c, Node) and c.tag in ("td", "th")])
        return grid(rows)


def grid(rows):
    """A markdown table from rows of already-escaped cell strings."""
    rows = [r for r in rows if r]
    if not rows:
        return ""
    w = max(len(r) for r in rows)
    rows = [r + [" "] * (w - len(r)) for r in rows]
    out = ["| " + " | ".join(rows[0]) + " |", "|" + " --- |" * w]
    out += ["| " + " | ".join(r) + " |" for r in rows[1:]]
    return "\n".join(out)


def _wrap(k):
    n = Node("x")
    n.kids.append(k)
    return n


def _find(n, tag):
    for k in n.kids:
        if isinstance(k, Node):
            if k.tag == tag:
                return k
            f = _find(k, tag)
            if f:
                return f
    return None


def _all(n, tag):
    for k in n.kids:
        if isinstance(k, Node):
            if k.tag == tag:
                yield k
            else:
                yield from _all(k, tag)


def md(html, course, figure, cell=False):
    t = Tree()
    t.feed(html or "")
    r = Md(course, figure)
    if cell:
        return r.inline(t.root, cell=True).strip()
    return "\n\n".join(p for p in r.blocks(t.root) if p.strip())


# ---------- pictures ----------

class Figures:
    """Copy a portal picture into Attachments once, and name it for an embed."""

    def __init__(self, course, dry):
        self.course, self.dry, self.copied, self.missing = course, dry, 0, []

    def __call__(self, src):
        if src.startswith("data:") or not src:
            self.missing.append(src[:40])
            return None
        path = ROOT / self.course / src
        if not path.exists():
            self.missing.append(src)
            return None
        name = path.name
        dest = ATTACH / name
        if dest.exists() and hashlib.md5(dest.read_bytes()).digest() != hashlib.md5(path.read_bytes()).digest():
            name = "%s-%s" % (self.course, path.name)       # a different picture already has the name
            dest = ATTACH / name
        if not dest.exists():
            self.copied += 1
            if not self.dry:
                shutil.copyfile(path, dest)
        return name


# ---------- job 1: curated notes -> charts ----------

def chart_md(lec, course, slug, fig):
    """One lecture's curated note as a chart region, in the vault's chart shape."""
    m = lambda h: md(h, course, fig)
    out = ["# Overview chart: <u>%s</u>" % (lec.get("title") or lec["name"])]
    if lec.get("framing"):
        out.append(m(lec["framing"]))
    for b in lec.get("blocks", []):
        t = b["t"]
        if t in ("note", "list"):
            out.append(m(b["html"]))
        elif t == "table":
            if b.get("lead"):
                out.append(m(b["lead"]))
            rows = [[md(c, course, fig, cell=True) or " " for c in b["cols"]]]
            rows += [[md(c, course, fig, cell=True) or " " for c in r] for r in b["rows"]]
            out.append(grid(rows))
        elif t == "figure":
            name = fig(b["src"])
            s = ("![[%s]]" % name) if name else "*[picture missing: %s]*" % b.get("alt", "")
            if b.get("cap"):
                s += "\n*%s*" % md(b["cap"], course, fig).replace("\n", " ")
            out.append(s)
        elif t == "pathway":
            out.append("```mermaid\n%s\n```" % b["mermaid"].strip())
        elif t == "callout":
            body = m(b["html"]).split("\n")
            head = "> [!%s] %s" % (b.get("kind") or "note", b.get("title") or "")
            out.append("\n".join([head.rstrip()] + [("> " + l).rstrip() for l in body]))
    if lec.get("keypoints"):
        out.append("**High-yield discriminators:** " + m(lec["keypoints"]))
    src = NOTE_SOURCE.get(slug) or NOTE_SOURCE.get(course)
    only_sr = all(b.get("title") == "Schulich Reviews" for b in lec.get("blocks", []))
    if only_sr or not src:
        src = "the Schulich Reviews, checked against this year's lectures"
    out.append("*Source: %s. Mirrored from the portal on %s.*" % (src, date.today().isoformat()))
    return "\n\n".join(out) + "\n\n---\n"


def split_front(text):
    """(frontmatter including its fences, the rest), or ('', text)."""
    m = re.match(r"^---\n.*?\n---\n", text, re.S)
    return (m.group(0), text[m.end():]) if m else ("", text)


def lecture_path(week_dir, lec):
    """The lecture's note in its Week folder, matched the way the roster read it.

    An unnumbered session (num "—") is filed under its bare name, and a stray
    double space in a vault file name must not cost the lecture its chart.
    """
    want = lec["name"] if lec["num"] == u"—" else "%s - %s" % (lec["num"], lec["name"])
    p = week_dir / (want + ".md")
    if p.exists() or not week_dir.is_dir():
        return p
    squash = lambda s: re.sub(r"\s+", " ", s).strip().lower()
    for f in week_dir.glob("*.md"):
        if squash(f.stem) == squash(want):
            return f
    return p


def charts(dry):
    for course, (cfolder, folders) in CHART_COURSES.items():
        fig = Figures(course, dry)
        added = skipped = missing = 0
        for f in sorted((ROOT / course / "data/notes").glob("*.json")):
            doc = json.load(io.open(f, encoding="utf-8"))
            slug = doc["block"]
            for w in doc["weeks"]:
                for lec in w["lectures"]:
                    if not lec.get("hasNote"):
                        continue
                    p = lecture_path(LECTURES / cfolder / folders[slug] / ("Week %d" % w["n"]), lec)
                    if not p.exists():
                        missing += 1
                        print("  no vault note: %s" % p.relative_to(VAULT), file=sys.stderr)
                        continue
                    text = io.open(p, encoding="utf-8").read().replace("\r\n", "\n")
                    front, rest = split_front(text)
                    if "# Overview chart" in rest.split("\n---\n")[0]:
                        skipped += 1
                        continue
                    if not front:
                        front = "---\ntype: LectureNote\ntags: LectureNote, -nograph\n---\n"
                    new = front + chart_md(lec, course, slug, fig) + "\n" + rest.lstrip("\n")
                    added += 1
                    if not dry:
                        io.open(p, "w", encoding="utf-8", newline="\n").write(new)
        print("%-5s charts added %d, already charted %d, no vault note %d, pictures copied %d, "
              "missing %d" % (course, added, skipped, missing, fig.copied, len(fig.missing)))


# ---------- job 2: question banks -> question notes ----------

def question_md(i, q, course, fig):
    m = lambda h: md(h, course, fig)
    out = ["# %d" % i, "<!-- qid: %s -->" % q["qid"]]
    oc = q.get("offCurriculum")
    if oc:
        out[-1] += "\n<!-- set: offcurriculum | reason: %s | qid: %s -->" % (oc.get("reason"), q["qid"])
    if q.get("retired"):
        out.append("*Retired on the portal; kept so its qid stays reserved.*")
    pre = q.get("preamble")
    if isinstance(pre, dict):
        pre = pre.get("html")
    if pre:
        out.append("\n".join("> " + l for l in m(pre).split("\n")))
    out.append(m(q["stem"]))
    opts = q.get("options") or []
    if opts:
        out.append("\n".join("%s) %s" % (o["letter"], md(o["html"], course, fig).replace("\n", " "))
                             for o in opts))
    if q.get("pairs"):
        # the pairs ARE the key, so the stem shows the right column sorted, not aligned
        p = q["pairs"]
        items = p.get("items") or []
        left = [md(it.get("left", ""), course, fig, cell=True) for it in items]
        right = sorted(set(md(it.get("right", ""), course, fig, cell=True) for it in items))
        rows = [[p.get("leftLabel") or "", p.get("rightLabel") or ""]]
        # a figure's own labels (A, B, 1, 2) already name themselves; lettering
        # them again would print "A. A"
        is_label = all(len(r) <= 3 for r in right)
        for k in range(max(len(left), len(right))):
            if k >= len(right):
                mark = " "
            elif is_label:
                mark = right[k]
            else:
                mark = "%s. %s" % (chr(65 + k), right[k])
            rows.append(["%d. %s" % (k + 1, left[k]) if k < len(left) else " ", mark])
        out.append(grid(rows))
    keyed = q.get("keyed", True) and not q.get("unscorable")
    head = "> [!q]- %s" % (q.get("answerTitle") or "Answer") if keyed else "> [!success]- Reasoned answer"
    body = m(q.get("answer") or "")
    out.append("\n".join([head] + [("> " + l).rstrip() for l in body.split("\n")]))
    for fl in q.get("flags") or []:
        kind = "warning" if fl.get("type") in ("warning", "error", "bug") else "note"
        if oc and fl.get("title") == "Off-curriculum":
            kind = "warning"
        lines = m(fl.get("html") or "").split("\n")
        out.append("\n".join(["> [!%s] %s" % (kind, fl.get("title") or "")] +
                             [("> " + l).rstrip() for l in lines]))
    return "\n\n".join(out)


def question_note(course, block, fam, qs, fig):
    cname = portal.BY_SLUG[course]["name"]
    fname = [f["name"] for f in portal.BY_SLUG[course]["families"] if f["key"] == fam][0]
    out = ["---\ntype: LectureNote\ntags: LectureNote, -nograph\n---",
           "*Backup of the portal's **%s** questions for **%s - %s**: %d questions, written from "
           "`%s/data/questions/%s.json` on %s. The portal JSON is the source; correct a question "
           "there and rerun `tools/vault_backup.py questions`. Each question's `qid` is in a "
           "comment under its number, and it is the key the portal's progress and Anki use.*"
           % (fname, cname, block["name"], len(qs), course, block["slug"], date.today().isoformat())]
    # an off-curriculum question carries a bare "Week N"; file it under the
    # heading its neighbours use for that week, so the note keeps one per week
    own = {}
    for q in qs:
        if q.get("family") != OFF and q.get("week") and q.get("weekLabel"):
            own.setdefault(q["week"], q["weekLabel"])
    by_week = {}
    for q in qs:
        label = q.get("weekLabel") or "Week unassigned"
        if q.get("family") == OFF:
            label = own.get(q.get("week"), label)
        by_week.setdefault((q.get("week") or 0, label), []).append(q)
    i = 0
    for (wn, label) in sorted(by_week):
        out.append("## " + label)
        lecture = None
        for q in by_week[(wn, label)]:
            lec = q.get("lecture") or "Unattributed"
            if lec != lecture:
                out.append("#### " + lec)
                lecture = lec
            i += 1
            out.append(question_md(i, q, course, fig))
    out.append(GENERATED)
    out.append("*Source: [[%s]]*" % ("99 - " + portal.BY_SLUG[course]["short"]
                                     if course != "t2c" else "00 - Practice Questions"))
    return "\n\n".join(out) + "\n"


def questions(dry):
    for c in portal.COURSES:
        course = c["slug"]
        fig = Figures(course, dry)
        wrote = n = 0
        folder = QUESTIONS / COURSE_FOLDER[course] if course in COURSE_FOLDER else QUESTIONS
        for b in c["blocks"]:
            slug, _, bname, _ = b
            block = {"slug": slug, "name": bname}
            f = ROOT / course / "data/questions" / ("%s.json" % slug)
            if not f.exists():
                continue
            qs = json.load(io.open(f, encoding="utf-8"))
            for fam in [x["key"] for x in c["families"]]:
                if (course, fam) in VAULT_OWNED or fam == OFF:
                    continue
                sel = [q for q in qs if home_family(q) == fam]
                if not sel:
                    continue
                p = folder / ("%s - %s.md" % (FAMILY_NOTE[fam], bname))
                if p.exists() and GENERATED not in io.open(p, encoding="utf-8").read():
                    print("  refusing to overwrite a hand-written note: %s"
                          % p.relative_to(VAULT), file=sys.stderr)
                    continue
                text = question_note(course, block, fam, sel, fig)
                wrote += 1
                n += len(sel)
                if not dry:
                    folder.mkdir(parents=True, exist_ok=True)
                    io.open(p, "w", encoding="utf-8", newline="\n").write(text)
        print("%-5s question notes %d, questions %d, pictures copied %d, missing %d"
              % (course, wrote, n, fig.copied, len(fig.missing)))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("job", choices=["charts", "questions"])
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    (charts if a.job == "charts" else questions)(a.dry_run)
